# Generated by Django 3.2.13 on 2022-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSAT_filtred_phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('created_by', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('deactivated_by', models.CharField(default=None, max_length=30, null=True)),
                ('deactivated_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
