# Generated by Django 3.2.13 on 2022-05-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csat_filtred_phones',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='csat_filtred_phones',
            name='deactivated_by',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
