# Generated by Django 3.2.13 on 2022-05-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220528_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csat_filtred_phones',
            name='deactivated_reason',
            field=models.TextField(default='', max_length=255, null=True),
        ),
    ]
