# Generated by Django 3.2.13 on 2022-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220528_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csat_filtred_phones',
            name='deactivated_reason',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csat_filtred_phones',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
