# Generated by Django 3.2.13 on 2022-05-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_csat_filtred_phones_is_deactivated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csat_filtred_phones',
            name='deactivated_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='csat_filtred_phones',
            name='is_deactivated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
