# Generated by Django 3.2.13 on 2022-05-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220528_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csat_filtred_phones',
            name='deactivated_reason',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
