# Generated by Django 3.2.13 on 2022-05-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_csat_filtred_phones_deactivated_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csat_filtred_phones',
            old_name='created_reason',
            new_name='creation_reason',
        ),
        migrations.RenameField(
            model_name='csat_filtred_phones',
            old_name='deactivated_reason',
            new_name='deactivation_reason',
        ),
    ]
